### ISSUE TITLE
modelTest (calling uncalibrate.CalGrid) does not recognize calibration curves

### ISSUE THREAD

**Issue by cmbarton** [ahb108/rcarbon#15]
I have a data.frame with columns for uncalibrated mean date, standard deviation, and the calibration curve to use. In the calibration curve column, I just use 'intcal13', 'marine13', and 'normal'. calibrate works fine and recognizes the calibration curves.

caldate_mesolithic <- calibrate(x=mesolithic_dates$C14mean, errors=mesolithic_dates$C14sdev, calCurves = mesolithic_dates$calib.curve,  normalised=FALSE, calMatrix=TRUE)

But when I try modelTest (using most of the parameters given in the example), it gives the error below. The problem seems to be in uncalibrated.CalGrid

nsim = 5
meso_model <- modelTest(caldate_mesolithic, errors = mesolithic_dates$C14sdev, timeRange = c(14000,5000), runm = 100, model="exponential", datenormalised=FALSE, nsim = nsim)

[1] "Aggregating observed dates..."
[1] "Monte-Carlo test..."
]Error in uncalibrate.CalGrid(as.CalGrid(predgrid), calCurves = unique.calCurves[i], : calCurves must be a character vector specifying one or more known curves or a custom three-column matrix/data.frame (see ?calibrate.default).

Here is the traceback:
4.stop("calCurves must be a character vector specifying one or more known curves or a custom three-column matrix/data.frame (see ?calibrate.default).")
3.uncalibrate.CalGrid(as.CalGrid(predgrid), calCurves = unique.calCurves[i], compact = FALSE, verbose = FALSE)
2.uncalibrate(as.CalGrid(predgrid), calCurves = unique.calCurves[i], compact = FALSE, verbose = FALSE)
1.modelTest(caldate_mesolithic, errors = mesolithic_dates$C14sdev, timeRange = c(14000, 5000), runm = 100, model = "exponential", datenormalised = FALSE, nsim = nsim)

**Comment by ercrema** [comment]
Thank you for the report Mike. This is likely caused by the presence of dates calibrated using 'normal' which is not supported by `uncalibrate()`. Could you test try running the same function removing from mesolithic_dates all instances `mesolithic_dates$calib.curve=='normal'` and see if the error still happens?  
This should have been specified in the help documentation (apologies for that) we will do this in the next patch version.

**Comment by cmbarton** [comment]
OK. I can do that. But ‘normal’ is supported by calibrate.

 

One other thing. I closed the issue with the corrupted help file, but perhaps it should be re-opened. Turns out that the github version does not install the vignettes folder or provide a link to your vignettes AFAICT.

 

I’m out for the next several hours but will try again without normal.

 

MIchael

 

_________________________________

 

C. Michael Barton

**Comment by ercrema** [comment]
we'll eventually make `normal` supported by `uncalibrate` but this is currently not the case.

re: vignettes:
does this happen with: 
`devtools::install_github('ahb108/rcarbon',build_vignettes=TRUE)`
by default `install_github` does not install the vignette. 

Was not able to reproduce the error you got in the CRAN install. Though it seems that is actually a problem with base R (see [here](https://github.com/r-lib/devtools/pull/1001) and not specific to rcarbon (see [here](https://github.com/ge11232002/CNEr/issues/17), and [here](https://stackoverflow.com/questions/34593159/failing-to-load-the-new-ggplot2-in-r) for similar issues). Removing, exiting R, and then re-installing should do.

**Comment by cmbarton** [comment]
I just tried this and it is not working. It hangs trying to install the vignettes. After a couple of tries, it said it needed roxygen, which I installed. But it still hangs.

 

devtools::install_github('ahb108/rcarbon',build_vignettes=TRUE)

Downloading GitHub repo ahb108/rcarbon@master

from URL https://api.github.com/repos/ahb108/rcarbon/zipball/master

Installing rcarbon

'/Library/Frameworks/R.framework/Resources/bin/R'  \

  --no-site-file --no-environ --no-save --no-restore  \

  --quiet CMD build  \

  '/private/var/folders/65/pp9w7z0d1mj502pj8hhl7vfw0000gn/T/RtmpR0XfTt/devtools173d7485b5a83/ahb108-rcarbon-80e80cc'  \

  --no-resave-data --no-manual 

 

* checking for file ‘/private/var/folders/65/pp9w7z0d1mj502pj8hhl7vfw0000gn/T/RtmpR0XfTt/devtools173d7485b5a83/ahb108-rcarbon-80e80cc/DESCRIPTION’ ... OK

* preparing ‘rcarbon’:

* checking DESCRIPTION meta-information ... OK

* installing the package to build vignettes

* creating vignettes ...

 

Then it just sits

 

MIchael

 

_________________________________

 

C. Michael Barton

**Comment by cmbarton** [comment]
It works if you don’t use the “normal” curve. Needs to be in the docs I guess.

 

Michael

 

_________________________________

 

C. Michael Barton

**Comment by ercrema** [comment]
That's normal the vignette contains functions with a fairly long processing time so it would take 20 -30 minutes to render depending on the machine (and yes you need roxygen). I would try again with the CRAN install which should work fine.
