### ISSUE TITLE
errors in testModel with long time series

### ISSUE THREAD

**Issue by cmbarton** [ahb108/rcarbon#16]
I'm interested in using rcarbon testModel in some long time series, but there seem to be some limits that are not quite clear. Below, I show a couple of tests I did with a set of Upper Paleolithic dates. I'm doing this on my MacBook, but it does have a Core i7 processor (4 effective cores from 2 hardware cores) and 16Gb RAM. 

test Model runs quickly in a few minutes when I set the time range to 19000-9000 years. But I get a vector memory exhausted error with a range of 20000-8000. And if I set the range a little higher, I get a different error about a limit of 50 iterations. Any thoughts as to what is happening here? 

See below

`azilian_model <- 
   modelTest(azilian_caldate, 
             errors = aziliandates_c14$C14sdev, 
             timeRange = c(25000,8000), 
             runm = 500, 
             model="exponential", 
             datenormalised=FALSE, 
             nsim = 100, 
             ncores = 4)`

[1] "Aggregating observed dates..."
[1] "Monte-Carlo test..."
Error in nls(y ~ exp(a + b * x), data = data.frame(x = time, y = finalSPD),  : 
  number of iterations exceeded maximum of 50

`azilian_model <- 
   modelTest(azilian_caldate, 
             errors = aziliandates_c14$C14sdev, 
             timeRange = c(20000,8000), 
             runm = 500, 
             model="exponential", 
             datenormalised=FALSE, 
             nsim = 100, 
             ncores = 4)`

[1] "Aggregating observed dates..."
[1] "Monte-Carlo test..."
Error: vector memory exhausted (limit reached?)

**Comment by ercrema** [comment]
The first error is related to model fitting - you should supply bespoke starter values for `nls()` (parameters `a` and `b` in `modelTest()`). The default works in most cases but occasionally fails, hence we included the option to specify the starter values. 

The second error message is a known issue for windows machine, though I understand with R 3.5 memory handling has changed for MacOSX too. A solution is provided in the help documentation of `modelTest()` under notes for windows machine, and requires the use of `memory.limit()` function. This should (hopefully) work also for MacOSX, in which case we'll need to remove "For windows user" bit in the note...

Notice that the model fitting comes before the heavy use of memory. This means that with 20-8k timespan the default starter values are fine but not with 25-8k. You didn't get the error message on vector memory because `modelTest()` stopped before...

**Comment by ercrema** [comment]
Ugh... just found out that `memory.limit()` is windows specific... Let me reproduce the error on my machine and will come back to you.

**Comment by ercrema** [comment]
I found many recently dated threads on `Error: vector memory exhausted (limit reached?)` - clearly other users and packages are having similar issues...

For the time being the solutions are one or more of the following: a) reduce the timeRange to a smaller interval (though it will require some tests); b) use `method=calsample` (this is not memory hungry at all so should be absolutely fine), c) increase `R_MAX_VSIZE` by setting the `.Renviron` file (though this might not work with larger timeSpan); d) revert back to R 3.4 (though this might not work with larger timeSpan either).

I hope this help - we are planning to improve the 'uncalsample' method to make it more efficient (both in terms of memory allocation and speed) but we haven't started working on this yet...

**Comment by cmbarton** [comment]
OK. Thanks for the suggestions. 

I can say for certain that 19000-9000 works (10000 years), but 20000-8000 does not (12000 years). So the limit is somewhere in that range. 
Is there any downside to using method=calsample? I can also try upping R_MAX_VSIZE and see what happens. I don't want to go back to 3.4. That would be a real PITA by now. 

This is not urgent but it does place limits on what I can do with the package of course. I hope you get time for the various updates to uncalibrated. 

With respect to the other error, any reasonable way to get estimates for a and b parameters to start nlm?

**Comment by cmbarton** [comment]
I just tried it with method=calsample. No problem with an extended time range (20000-6000), and it seems to run much faster. But it gives rather different results, even when I use the same time ranges. I also get VERY different results when I set a time range of 20000-6000 vs. 19000-9000 (about the max range of the SPD curve). I don't understand why they should differ so much. Any reason to prefer uncalsample to calsample methods?

**Comment by cmbarton** [comment]
Interestingly, if I use method='calsample', I don't get either of the errors I listed. No nls iteration either either. I tried this on a different, smaller sample of dates. Without method='calsample', I got the nls error without getting the vector memory error on a range of 10000 years (i.e., a range that works with a different groups of samples). Like I mentioned before, I get quite different results with a long time range and method='calsample' than I do with a short time range and the default uncalsample method. 

Specifically, considerably more of the SPD curve falls outside the 95% CI with the calsample method, especially with a longer time range. This is important for me to understand because I'm interested in looking at some longish time ranges (e.g., 35k-8k BP) and comparing different sets of date samples.

**Comment by ercrema** [comment]
Changing the time range will affect the results as the theoretical model will be different,  unless you don't have a perfect exponential growth. The choice of `method` shouldn't affect this, so not sure why this happened. Perhaps an random accident of `nls` iterations? Would be great if you can check if this happens all the time and settling random seeds. Also if the observed pattern is very different front an exponential growth you might have hard time with the spd fitting...

Re  the difference between 'calsample' and 'uncalsample'. The short answer is that the former is the original method where individual dates are sampled, uncalibrated and calibrated back, the latter is an alternative approach that Andy Bevan introduced consisting of uncalibrating the whole fitted model first,  followed by sampling and calibration. We are writing a paper about this (though start of term does not help!), but the key differences is that the latter approach can better emulate the artificial peaks when normalised dates are used. Perhaps Andy can step in and provide a better summary (I think he introduced this is the quaternary science reviews paper?). With unnormalised dates and smoothing the two approaches shouldn't really be that different, so I'm curious to find out more. Would you mind sending me just the output of `modelTest`? I don't need the raw data, just the fitted model (`$fit` and `$fitobject`) so can run some tests when I have time.

**Comment by ahb108** [comment]
Yes, just to add that the difference in envelopes should be considerable in the pre-Holocene where the normalisation effects (that appear as spikes) are sharper. But I agree that your issue with a changing fit shape should be down only to the time range you are fitting to (and choice of seed).

**Comment by cmbarton** [comment]
I'm attaching the model output for the following code, using method='calsample' and method='uncalsample', and also graphs of the results where you can see the difference. 

![azilian_calsample](https://user-images.githubusercontent.com/8967599/46694640-48300280-cbc2-11e8-83f5-ed9b35af0d2a.png)

![azilian_uncalsample](https://user-images.githubusercontent.com/8967599/46694641-48300280-cbc2-11e8-9cef-a3dfd69bb619.png)

Guess I can't attach the model output. I will send a link by email.

**Comment by cmbarton** [comment]
I could not put them onto GitHub in my comment so I am emailing. 

Here is a link to the model output files (too big to send): 

 

https://www.dropbox.com/s/c4fr7yr7deax8b0/azilian_model_calsample.rda?dl=0

https://www.dropbox.com/s/y7q2u6u1gzma81u/azilian_model_uncalsample.rda?dl=0 

 

Michael

**Comment by ercrema** [comment]
Can you send us also the exact code you used from the calibration onwards?

**Comment by cmbarton** [comment]
I put it into my comment on github

 

Michael

**Comment by ercrema** [comment]
Never mind I got most out of the output files... The fitted models are the same, so clearly the difference is coming from the two methods. Will look into this, it would be great if you could share with us your raw data as well, but I understand if you prefer not to.

**Comment by cmbarton** [comment]
It’s not showing up on github again. So here it is in case you need it:

 

azilian_model <- 

  modelTest(azilian_caldate, 

            errors = aziliandates_c14$C14sdev, 

            timeRange = c(19000,9000), 

            runm = 500, 

            model="exponential", 

            datenormalised=FALSE, 

            nsim = 100, 

            ncores = 4, method = 'uncalsample')

 

azilian_model <- 

  modelTest(azilian_caldate, 

            errors = aziliandates_c14$C14sdev, 

            timeRange = c(19000,9000), 

            runm = 500, 

            model="exponential", 

            datenormalised=FALSE, 

            nsim = 100, 

            ncores = 4, method = 'calsample')

**Comment by ercrema** [comment]
Could you check if the difference can be observed using ncores=1?

**Comment by ercrema** [comment]
@ahb108 I think the following line 
``` cragrids[[i]] <- tmp.grid[tmp.grid$CRA <= max(x$metadata$CRA) & tmp.grid$CRA >= min(x$metadata$CRA),]```
found [here](https://github.com/ahb108/rcarbon/blob/2ce3fa34a13083fc80a77c4e136845a1bb1e66df/R/tests.R#L153) is causing the edge effect. It's basically limiting the range of the output of `uncalibrate()` to the observed range of CRA in the input dates, which does not happen in the 'calsample' approach as it directly samples from the fitted model in calendar time. I think this line was already there from the beginning (it was on rcarbon 1.1.3 before I made changes in `modelTest()`, see  [here](https://github.com/ahb108/rcarbon/blob/c4fcc9a18b6d6fa6a3e2be680e2e750fe1821624/R/tests.R#L127-L128)). I'm tempted to remove this, as it essentially overrides the user request to simulate the model to a specific timeRange? I reckon if one uses an absurdly larger timeSpan beyond the observed range this will become even more evident. 

The dent between 14k and 12k is probably due to the expected differences between calsample and uncalsample that is further infated by the difference in time range from which the samples are taken from in the two methods.

**Comment by cmbarton** [comment]
OK. So this is a bug of sorts. I have a couple of more general questions about the methods. Is this a good place (for a record) or better to do so directly to you and Andy via email?

**Comment by ercrema** [comment]
If not's specific to bits of code but more in general about the method I think a direct email would be better

**Comment by ercrema** [comment]
Commit d73ca3a fixes the issue of differences in the time span of the simulation envelope for the two methods. More details in the help documentation.
