### ISSUE TITLE
no underscores in site names?

### ISSUE THREAD

**Issue by cmbarton** [ahb108/rcarbon#17]
alldate_bins <- binPrep(alldates$site, alldates$C14mean, 100)
Error in binPrep(alldates$site, alldates$C14mean, 100) : 
  sites should not contain elements with underscores

Why???

These are strings.

**Comment by ercrema** [comment]
Because bin names are created using underscores after the original site names.

**Comment by cmbarton** [comment]
Needs to go into docs then. 

"sites | a vector of character strings (or number to coerce to character) of all sites or site phases"

From binPrep docs
Any other restrictions?

**Comment by ercrema** [comment]
Yes, you're right I was about to reopen the issue to set a reminder. No other restrictions in the naming I  can think of.

**Comment by ercrema** [comment]
Yes, you're right I was about to reopen the issue to set a reminder. No other restrictions in the naming I  can think of.

**Comment by ercrema** [comment]
Added documentation in commit 5dfea721
