### ISSUE TITLE
Error reporting: empty or unrecognised calibration curve

### ISSUE THREAD

**Issue by tcwilkinson** [ahb108/rcarbon#24]
Providing `calibrate` with an empty or unrecognised `calCurves` calibration curve provides the cryptic error message which is difficult to solve:
```
Error in file(con, "r") : cannot open the connection
```
Before reading `readLines(calCurveFile, encoding = "UTF-8")`, can calibrate check with file.exists first?

**Comment by ercrema** [comment]
I am not able to reproduce the error:

`calibrate(3000,30,calCurves='')`

returns correctly:

`Error in calibrate.default(3000, 30, calCurves = "") : 
  calCurves must be a character vector specifying one or more known curves or a custom three-column matrix/data.frame (see ?calibrate.default).`

and `calibrate(3000,30,calCurves='intcal15')`

returns also correctly:

`Error in calibrate.default(3000, 30, calCurves = "") : 
  calCurves must be a character vector specifying one or more known curves or a custom three-column matrix/data.frame (see ?calibrate.default).`

**Comment by tcwilkinson** [comment]
Aha, so further testing and it seems to be only on NULL:

`calibrate(3000,30,calCurves=NULL)`

returns:
`Error in file(con, "r") : cannot open the connection`

In my case, it was because of a misnamed column in a data.frame was returning NULL instead of the vector of dates. (I had thought it was because the contents was "" not NULL).

**Comment by ercrema** [comment]
Error message added for NULL and NA values in the `calCurves` argument (commit dfb68c383e7cd4f4148c10224682efe7aa6da95c)
