### ISSUE TITLE
Typo in modelTest?

### ISSUE THREAD

**Issue by dieza** [ahb108/rcarbon#30]
Shouldn't be this two instances of CalBP in test.R uncapitalized?
208	    if (!all(colnames(predgrid)%in%c("CalBP","PrDens")))
209	    {
210		    stop("Column names in the predgrid argument should be 'CalBP' and 'PrDens'")

**Comment by ercrema** [comment]
Thank you for spotting this! Fixed in 8a0f278ded4eb833b64b8f3d96efa6c1094fe00c
