### ISSUE TITLE
modelTest fails in R 4.x

### ISSUE THREAD

**Issue by cmbarton** [ahb108/rcarbon#38]
I am trying to use modelTest, with the same code as I used successfully earlier this year. The only difference is that I've updated to R 4.0.2

It now always fails with the error:

"Error in makePSOCKcluster(names = spec, ...) : 
  Cluster setup failed. 1 worker of 1 failed to connect."

Here is my code. I've specified the number of cores or simply left out that argument with the only difference being the number of "workers" that "failed to connect."

`model.all <- LUP_Meso_dates %>% 
 dplyr::filter(date.COV<=0.1 & cal.curve != "normal") %>% 
  with(., calibrate(x=date.BP.mean, errors=date.BP.SD, calCurves = cal.curve, normalised=TRUE, calMatrix=FALSE)) %>% 
  modelTest(., 
            errors = subset(LUP_Meso_dates, C14.COV<=0.1 & cal.curve != "normal")$C14sdev, 
            timeRange = c(10000,8000), 
            runm = 500, 
            model="exponential", 
            datenormalised=TRUE, 
            nsim = 200,
            method = 'calsample', 
            bins = date.bins)`

I'm using a Mac. It has failed with both Mac OS X 14 and 15. It failed with the binary and with the most current source code from this Git repository.

**Comment by ercrema** [comment]
Hi Mike, 
Thanks for raising the issue. Could you run the code below and let me know if you get that error message?

```
library(foreach)
library(parallel)
library(doParallel)
ncores=1
cl <- parallel::makeCluster(ncores)
doParallel::registerDoParallel(cl)
```
The error is from the `parallel` package for parallel processing. The fact that this happens even if `ncores` is set to 1 is because `modelTest()` has been changed since rcarbon 1.3.1 and has now the above is executed even if you run over a single processor. If you do get the same error running the script above it means that this was likely caused by something related to [this thread](https://github.com/rstudio/rstudio/issues/6692).  It seems that for Mac+Rstudio+R4.0 users we need to wait for a patch in the parallel package. Could you test (after re-starting your session) the following and see if you can register the cores via the `snow` package?

```
library(foreach)
library(doSNOW)
ncores = 1
cl <- snow::makeCluster(ncores)
registerDoSNOW(cl)
```

**Comment by cmbarton** [comment]
> Hi Mike,
> Thanks for raising the issue. Could you run the code below and let me know if you get that error message?
> 
> ```
> library(foreach)
> library(parallel)
> library(doParallel)
> ncores=1
> cl <- parallel::makeCluster(ncores)
> doParallel::registerDoParallel(cl)
> ```
> 
> The error is from the `parallel` package for parallel processing. The fact that this happens even if `ncores` is set to 1 is because `modelTest()` has been changed since rcarbon 1.3.1 and has now the above is executed even if you run over a single processor. If you do get the same error running the script above it means that this was likely caused by something related to [this thread](https://github.com/rstudio/rstudio/issues/6692). It seems that for Mac+Rstudio+R4.0 users we need to wait for a patch in the parallel package. Could you test (after re-starting your session) the following and see if you can register the cores via the `snow` package?
> 
> ```
> library(foreach)
> library(doSNOW)
> ncores = 1
> cl <- snow::makeCluster(ncores)
> registerDoSNOW(cl)
> ```

Here is the result of the first test. It took a long time for this to finish and return the error. 

> library(foreach)
> library(parallel)
> library(doParallel)
Loading required package: iterators
> ncores=1
> cl <- parallel::makeCluster(ncores)

Attaching package: ‘dplyr’

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Error in makePSOCKcluster(names = spec, ...) : 
  Cluster setup failed. 1 worker of 1 failed to connect.
> doParallel::registerDoParallel(cl)
Error in doParallel::registerDoParallel(cl) : object 'cl' not found

**Comment by cmbarton** [comment]
Here is the result of the 2nd test, after restarting R

> library(foreach)
> library(doSNOW)
Error in library(doSNOW) : there is no package called ‘doSNOW’
> ncores = 1
> cl <- snow::makeCluster(ncores)

Attaching package: ‘dplyr’

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

> registerDoSNOW(cl)
Error in registerDoSNOW(cl) : could not find function "registerDoSNOW"

**Comment by cmbarton** [comment]
Needed to install DoSNOW. Now it works.

> library(foreach)
> library(doSNOW)
Loading required package: iterators
Loading required package: snow
> ncores = 1
> cl <- snow::makeCluster(ncores)

Attaching package: ‘dplyr’

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

> registerDoSNOW(cl)

**Comment by cmbarton** [comment]
Is the original problem in parallel or in doParallel? the latter has not been updated for a year, but parallel was updated in late June.

**Comment by cmbarton** [comment]
After reading the thread, I just updated to RStudio 1.3.1056, dated 7 July 2020. This seems to fix the problem.

**Comment by ercrema** [comment]
Great - we might move to `doSNOW` anyway as it enables a handy progress bar for multicore processing.
