### ISSUE TITLE
modelTest() does not accept "intcal20", "shcal20", or "marine20" as a calCurves argument

### ISSUE THREAD

**Issue by philriris** [ahb108/rcarbon#43]
Amended function:

modelTest <- function (x, errors, nsim, bins = NA, runm = NA, timeRange = NA, 
          backsight = 50, changexpr = expression((t1/t0)^(1/d) - 1), 
          gridclip = TRUE, raw = FALSE, model = c("exponential"), 
          method = c("uncalsample"), predgrid = NA, normalised = NA, 
          datenormalised = NA, spdnormalised = FALSE, ncores = 1, fitonly = FALSE, 
          a = 0, b = 0, edgeSize = 500, verbose = TRUE) 
{
  caltimeRange = c(55000, 0)
  if (any(x$metadata$CalCurve %in% c("intcal13", "shcal13", "intcal20", "marine20", "shcal20",
                                     "marine13", "intcal13nhpine16", "shcal13shkauri16"))) {
    caltimeRange = c(50000, 0)
  }
  if (fitonly == TRUE) {
    nsim <- 1
  }
  if (ncores > 1 & !requireNamespace("doSNOW", quietly = TRUE)) {
    warning("the doParallel package is required for multi-core processing; ncores has been set to 1")
    ncores = 1
  }
  else {
    cl <- snow::makeCluster(ncores)
    registerDoSNOW(cl)
    on.exit(snow::stopCluster(cl))
  }
  if (!any(method %in% c("uncalsample", "calsample"))) {
    stop("The 'method' argument must be either 'uncalsample' or 'calsample'")
  }
  ccrange = c(max(medCal(x)), min(medCal(x)))
  if (anyNA(timeRange)) {
    timeRange = ccrange
  }
  if (is.na(normalised)) {
    normalised = FALSE
    if (x$metadata$Normalised[1] == TRUE) {
      normalised = TRUE
    }
  }
  if (normalised != x$metadata$Normalised[1]) {
    warning("The normalisation setting of x and normalised are different")
  }
  if (!is.na(datenormalised)) {
    if (datenormalised != normalised) {
      warning("'datenormalised' is not equal to 'normalised'. The datenormalised setting will be used for the normalisation setting of the calibration of simulated dates")
      normalised = datenormalised
    }
    if (datenormalised != x$metadata$Normalised[1]) {
      if (x$metadata$Normalised[1]) {
        warning("Input dates are normalised but datenormalised is set to FALSE. The datenormalised setting will be ignored")
        normalised = datenormalised
      }
      if (!x$metadata$Normalised[1]) {
        warning("Input dates are not normalised but datenormalised is set to TRUE. The datenormalised setting will be ignored")
        normalised = datenormalised
      }
    }
  }
  calCurves = x$metadata$CalCurve
  if (!all(calCurves %in% c("intcal13", "shcal13", "intcal20", "marine20", "shcal20",
                            "marine13", "intcal13nhpine16", "shcal13shkauri16"))) {
    stop("modelTest() currently accepts only dates calibrated with the following calibration curves: 'intcal13','intcal13nhpine16','shcal13','shcal13shkauri16', and 'marine13'")
  }
  unique.calCurves = as.character(sort(unique(calCurves)))
  ncc = length(unique.calCurves)
  if (verbose) {
    print("Aggregating observed dates...")
  }
  if (is.na(bins[1])) {
    samplesize <- t(matrix(table(calCurves), nrow = ncc, 
                           ncol = nsim))
    colnames(samplesize) = names(table(calCurves))
  }
  else {
    samplesize <- curveSamples(bins = bins, calCurves = calCurves, 
                               nsim = nsim)
    if (ncc == 1) {
      samplesize = matrix(samplesize, ncol = 1, nrow = length(samplesize))
      colnames(samplesize) = names(table(calCurves))
    }
  }
  if (ncc > 1) {
    samplesize = samplesize[, unique.calCurves]
  }
  if (is.na(bins[1])) {
    bins <- as.character(1:nrow(x$metadata))
  }
  observed <- spd(x = x, bins = bins, timeRange = timeRange, 
                  runm = runm, spdnormalised = spdnormalised, verbose = FALSE, 
                  edgeSize = edgeSize)
  finalSPD <- observed$grid$PrDens
  sim <- matrix(NA, nrow = length(finalSPD), ncol = nsim)
  if (verbose & !fitonly) {
    print("Monte-Carlo test...")
    flush.console()
  }
  fit.time <- seq(timeRange[1], timeRange[2], -1)
  pred.time <- fit.time
  if (gridclip) {
    st = max(ccrange[1], timeRange[1]) + edgeSize
    en = min(ccrange[2], timeRange[2]) - edgeSize
    pred.time <- seq(st, en, -1)
  }
  fit <- NA
  if (model == "exponential") {
    fit <- nls(y ~ exp(a + b * x), data = data.frame(x = fit.time, 
                                                     y = finalSPD), start = list(a = a, b = b))
    est <- predict(fit, list(x = pred.time))
    predgrid <- data.frame(calBP = pred.time, PrDens = est)
  }
  else if (model == "uniform") {
    predgrid <- data.frame(calBP = pred.time, PrDens = mean(finalSPD))
  }
  else if (model == "linear") {
    fit <- lm(y ~ x, data = data.frame(x = fit.time, y = finalSPD))
    est <- predict(fit, list(x = pred.time))
    predgrid <- data.frame(calBP = pred.time, PrDens = est)
  }
  else if (model == "custom") {
    if (length(predgrid) != 2) {
      stop("If you choose a custom model, you must provide a proper predgrid argument (two-column data.frame of calBP and predicted densities).")
    }
    if (!all(colnames(predgrid) %in% c("calBP", "PrDens"))) {
      stop("Column names in the predgrid argument should be 'calBP' and 'PrDens'")
    }
  }
  else {
    stop("Specified model not one of current choices.")
  }
  if (fitonly) {
    print("Done (SPD and fitted model only).")
    predgrid <- subset(predgrid, calBP <= timeRange[1] & 
                         calBP >= timeRange[2])
    res <- list(result = NA, sim = NA, pval = NA, osbSPD = observed, 
                fit = predgrid, fitobject = fit)
    return(res)
  }
  if (edgeSize > 0) {
    predgrid = rbind.data.frame(data.frame(calBP = (max(predgrid$calBP) + 
                                                      edgeSize):c(predgrid$calBP[1] + 1), PrDens = 0), 
                                predgrid)
    predgrid = rbind.data.frame(predgrid, data.frame(calBP = min(predgrid$calBP):(min(predgrid$calBP) - 
                                                                                    edgeSize), PrDens = 0))
    if (any(predgrid$calBP <= 0 | predgrid$calBP >= caltimeRange[1])) {
      warning("edgeSize reduced")
      predgrid = subset(predgrid, calBP <= caltimeRange[1] & 
                          calBP >= 0)
    }
  }
  cragrids = vector("list", length = ncc)
  for (i in 1:ncc) {
    tmp.grid <- uncalibrate(as.CalGrid(predgrid), calCurves = unique.calCurves[i], 
                            compact = FALSE, verbose = FALSE)
    cragrids[[i]] <- tmp.grid
    if (gridclip) {
      cragrids[[i]] <- tmp.grid[tmp.grid$CRA <= max(x$metadata$CRA) & 
                                  tmp.grid$CRA >= min(x$metadata$CRA), ]
    }
  }
  opts = NULL
  if (verbose) {
    if (ncores > 1) {
      print(paste("Running in parallel on ", getDoParWorkers(), 
                  " workers...", sep = ""))
    }
    pb <- txtProgressBar(min = 0, max = nsim, style = 3)
    progress <- function(n) setTxtProgressBar(pb, n)
    opts <- list(progress = progress)
  }
  if (ncores == 1) {
    for (s in 1:nsim) {
      if (verbose) {
        setTxtProgressBar(pb, s)
      }
      if (method == "uncalsample") {
        randomDates <- vector("list", length = ncc)
        ccurve.tmp <- numeric()
        for (i in 1:ncc) {
          randomDates[[i]] = sample(cragrids[[i]]$CRA, 
                                    replace = TRUE, size = samplesize[s, i], 
                                    prob = cragrids[[i]]$PrDens)
          ccurve.tmp = c(ccurve.tmp, rep(unique.calCurves[i], 
                                         samplesize[s, i]))
        }
        randomSDs <- sample(size = length(unlist(randomDates)), 
                            errors, replace = TRUE)
      }
      if (method == "calsample") {
        randomDates <- vector("list", length = ncc)
        ccurve.tmp <- numeric()
        for (i in 1:ncc) {
          randomDates[[i]] = sample(cragrids[[i]]$CRA, 
                                    replace = TRUE, size = samplesize[s, i], 
                                    prob = cragrids[[i]]$Raw)
          ccurve.tmp = c(ccurve.tmp, rep(unique.calCurves[i], 
                                         samplesize[s, i]))
        }
        randomSDs <- sample(size = length(unlist(randomDates)), 
                            errors, replace = TRUE)
      }
      tmp <- calibrate(x = unlist(randomDates), errors = randomSDs, 
                       timeRange = timeRange, calCurves = ccurve.tmp, 
                       normalised = normalised, ncores = 1, verbose = FALSE, 
                       calMatrix = TRUE)
      simDateMatrix <- tmp$calmatrix
      sim[, s] <- apply(simDateMatrix, 1, sum)
      sim[, s] <- (sim[, s]/sum(sim[, s])) * sum(predgrid$PrDens[predgrid$calBP <= 
                                                                   timeRange[1] & predgrid$calBP >= timeRange[2]])
      if (spdnormalised) {
        sim[, s] <- (sim[, s]/sum(sim[, s]))
      }
      if (!is.na(runm)) {
        sim[, s] <- runMean(sim[, s], runm, edge = "fill")
      }
    }
  }
  if (ncores > 1) {
    sim <- foreach(s = 1:nsim, .combine = "cbind", 
                   .packages = "rcarbon", .options.snow = opts) %dopar% 
      {
        randomDates <- vector("list", length = ncc)
        ccurve.tmp <- numeric()
        if (method == "uncalsample") {
          for (i in 1:ncc) {
            randomDates[[i]] = sample(cragrids[[i]]$CRA, 
                                      replace = TRUE, size = samplesize[s, i], 
                                      prob = cragrids[[i]]$PrDens)
            ccurve.tmp = c(ccurve.tmp, rep(unique.calCurves[i], 
                                           samplesize[s, i]))
          }
        }
        if (method == "calsample") {
          for (i in 1:ncc) {
            randomDates[[i]] = sample(cragrids[[i]]$CRA, 
                                      replace = TRUE, size = samplesize[s, i], 
                                      prob = cragrids[[i]]$Raw)
            ccurve.tmp = c(ccurve.tmp, rep(unique.calCurves[i], 
                                           samplesize[s, i]))
          }
        }
        randomSDs <- sample(size = length(unlist(randomDates)), 
                            errors, replace = TRUE)
        tmp <- calibrate(x = unlist(randomDates), errors = randomSDs, 
                         timeRange = timeRange, calCurves = ccurve.tmp, 
                         normalised = normalised, ncores = 1, verbose = FALSE, 
                         calMatrix = TRUE)
        simDateMatrix <- tmp$calmatrix
        aux <- apply(simDateMatrix, 1, sum)
        aux <- (aux/sum(aux)) * sum(predgrid$PrDens[predgrid$calBP <= 
                                                      timeRange[1] & predgrid$calBP >= timeRange[2]])
        if (spdnormalised) {
          aux <- (aux/sum(aux))
        }
        if (!is.na(runm)) {
          aux <- runMean(aux, runm, edge = "fill")
        }
        aux
      }
  }
  if (verbose) {
    close(pb)
  }
  timeSequence = timeRange[1]:timeRange[2]
  foo = function(spd, backsight, timeSequence, changexpr) {
    obs = rep(NA, length(timeSequence))
    for (i in 1:c(length(obs) - backsight)) {
      d = backsight
      t0 = spd[i]
      t1 = spd[i + backsight]
      obs[i + backsight] = eval(changexpr)
      if (t1 == 0 | t0 == 0) {
        obs[i + backsight] = NA
      }
    }
    return(obs)
  }
  obs.roc = foo(finalSPD, backsight = backsight, timeSequence = timeSequence, 
                changexpr = changexpr)
  sim.roc = apply(sim, 2, foo, backsight = backsight, timeSequence = timeSequence, 
                  changexpr = changexpr)
  lo <- apply(sim, 1, quantile, prob = 0.025, na.rm = TRUE)
  hi <- apply(sim, 1, quantile, prob = 0.975, na.rm = TRUE)
  lo.roc = apply(sim.roc, 1, quantile, prob = 0.025, na.rm = TRUE)
  hi.roc = apply(sim.roc, 1, quantile, prob = 0.975, na.rm = TRUE)
  Zsim <- t(apply(sim, 1, scale))
  zLo <- apply(Zsim, 1, quantile, prob = 0.025, na.rm = TRUE)
  zHi <- apply(Zsim, 1, quantile, prob = 0.975, na.rm = TRUE)
  Zsim.roc <- t(apply(sim.roc, 1, scale))
  zLo.roc <- apply(Zsim.roc, 1, quantile, prob = 0.025, na.rm = TRUE)
  zHi.roc <- apply(Zsim.roc, 1, quantile, prob = 0.975, na.rm = TRUE)
  Zscore_empirical <- (finalSPD - apply(sim, 1, mean))/apply(sim, 
                                                             1, sd)
  Zscore_empirical.roc <- (obs.roc - apply(sim.roc, 1, mean))/apply(sim.roc, 
                                                                    1, sd)
  busts <- which(Zscore_empirical < zLo)
  booms <- which(Zscore_empirical > zHi)
  busts2 <- which(finalSPD < lo)
  booms2 <- which(finalSPD > hi)
  busts.roc <- which(Zscore_empirical.roc < zLo.roc)
  booms.roc <- which(Zscore_empirical.roc > zHi.roc)
  busts2.roc <- which(obs.roc < lo.roc)
  booms2.roc <- which(obs.roc > hi.roc)
  observedStatistic <- sum(c(zLo[busts] - Zscore_empirical[busts]), 
                           c(Zscore_empirical[booms] - zHi[booms]))
  observedStatistic.roc <- sum(c(zLo.roc[busts.roc] - Zscore_empirical.roc[busts.roc]), 
                               c(Zscore_empirical.roc[booms.roc] - zHi.roc[booms.roc]))
  expectedstatistic <- abs(apply(Zsim, 2, function(x, y) {
    a = x - y
    i = which(a < 0)
    return(sum(a[i]))
  }, y = zLo)) + apply(Zsim, 2, function(x, y) {
    a = x - y
    i = which(a > 0)
    return(sum(a[i]))
  }, y = zHi)
  expectedstatistic.roc <- abs(apply(Zsim.roc, 2, function(x, 
                                                           y) {
    a = x - y
    i = which(a < 0)
    return(sum(a[i]))
  }, y = zLo.roc)) + apply(Zsim.roc, 2, function(x, y) {
    a = x - y
    i = which(a > 0)
    return(sum(a[i]))
  }, y = zHi.roc)
  pvalue <- c(length(expectedstatistic[expectedstatistic > 
                                         observedStatistic]) + 1)/c(nsim + 1)
  pvalue.roc <- c(length(expectedstatistic.roc[expectedstatistic.roc > 
                                                 observedStatistic.roc]) + 1)/c(nsim + 1)
  result <- data.frame(calBP = observed$grid$calBP, PrDens = finalSPD, 
                       lo = lo, hi = hi)
  result.roc <- data.frame(calBP = timeSequence, roc = obs.roc, 
                           lo.roc = lo.roc, hi.roc = hi.roc)
  predgrid <- subset(predgrid, calBP <= timeRange[1] & calBP >= 
                       timeRange[2])
  if (raw == FALSE) {
    sim <- NA
    sim.roc <- NA
  }
  res <- list(result = result, result.roc = result.roc, sim = sim, 
              sim.roc = sim.roc, pval = pvalue, pval.roc = pvalue.roc, 
              fit = predgrid, fitobject = fit, nbins = length(unique(bins)), 
              n = nrow(x$metadata), nsim = nsim, backsight = backsight)
  class(res) <- "SpdModelTest"
  if (verbose) {
    print("Done.")
  }
  return(res)
}

**Comment by ercrema** [comment]
Fixed with commit 527884ce3c519b7607bbfdd72776c721f3437acd
