### ISSUE TITLE
tidyverse packages don't recognise calGrid objects as data frames

### ISSUE THREAD

**Issue by joeroe** [ahb108/rcarbon#47]
Version 1.0.0 of dplyr included a breaking change that requires extra classes to be added before the classes they extend, not after (see [dplyr v.1.0.0 release notes](https://github.com/tidyverse/dplyr/releases/tag/v1.0.0), tidyverse/dplyr#5066, and r-lib/vctrs#972). I couldn't find a full explanation for this change, but I assume the logic is that because R dispatches S3 classes in the order they're listed, they should be ordered from least to most generic.

rcarbon seems to mostly prepend extra classes, except for the `calGrid` class produced by `calibrate()`: 

```r
> calibrated <- rcarbon::calibrate(c(1000,2000,3000), rep(50, 3))
> class(calibrated)
[1] "CalDates" "list"    
> class(calibrated$grids[[1]])
[1] "data.frame" "calGrid" 
```

This means that various tidyverse packages no longer recognise calGrids as data frames. For example, if you want to extract them into a table, it will throw an error unless you first rewrite the class vector:

```r
> caltable <- dplyr::tibble(id = c(1,2,3), calgrid = calibrated$grid)
> tidyr::unnest(caltable, calgrid)
Error: Input must be a vector, not a `data.frame/calGrid` object.

> caltable$calgrid <- lapply(caltable$calgrid, function(x) {
+   class(x) <- rev(class(x))
+   return(x)
+ })
> tidyr::unnest(caltable, calgrid)
# A tibble: 1,299 x 3
      id calBP    PrDens
   <dbl> <dbl>     <dbl>
 1     1  1170 0.0000157
 2     1  1169 0.0000168
 3     1  1168 0.0000181
 4     1  1167 0.0000195
 5     1  1166 0.0000210
 6     1  1165 0.0000225
 7     1  1164 0.0000186
 8     1  1163 0.0000153
 9     1  1078 0.0000135
10     1  1077 0.0000141
# … with 1,289 more rows
```

The fix should be a simple case of making sure calGrid is always prepended to existing classes rather than appended – I'd be happy to submit a pull request if you don't think it will cause problems elsewhere?

**Comment by ercrema** [comment]
Thanks @joeroe - fixed in 4633f0beb2cce02877faa37f478c04f5ea53a0d4
