### ISSUE TITLE
uncalibrate documentation error

### ISSUE THREAD

**Issue by archaeometer** [ahb108/rcarbon#49]
The uncalibrate documentation says
   roundyear | An optional vector of IDs for each date (ignored if x is a CalGrid object).
but supplying IDs generates an error message

> uncalibrate(1000,25,roundyear = "Test-34")
Error in if (roundyear) { : argument is not interpretable as logical

Examning the code in  rcarbon:::uncalibrate.default, roundyear seems to be a logical indicating whether to round dates or not.

**Comment by ercrema** [comment]
Thanks Andrew - must have been a copy and paste error in the documentation. Fixed in f33dd807347ee77cf4cbd00e919a86f85758cac2
