### ISSUE TITLE
Error drawing a polygon of class SpdModelTest

### ISSUE THREAD

**Issue by dieza** [ahb108/rcarbon#51]
I got an error when printing a SpdModelTest.
plot(expnull,type='roc',main="Roc")
rcarbon_1.4.1
![expnull](https://user-images.githubusercontent.com/3057651/101015073-1d098980-3567-11eb-8936-831519258fb2.png)

**Comment by ercrema** [comment]
Hi Dieza, we need more details to replicate this. Would you mind sharing your code and data?

**Comment by dieza** [comment]
No I don't, actually I'tried to upload a Rdata file with the object with no success. Any ideas?

**Comment by ercrema** [comment]
You can drop me an email with the RData and the code you used to generate `expnull` and I will look at this once I have a moment.

**Comment by ercrema** [comment]
Fixed with commit 69b4e06a66715e764cb1375892cf968d1c24c463
