### ISSUE TITLE
No filling color in the proportion option of plot

### ISSUE THREAD

**Issue by dieza** [ahb108/rcarbon#52]
When trying to reproduce the vignette with my own data, the _proportion_ type of plot of the stackspd function doesn´t fill one of the three areas.
![comparando_SPD2](https://user-images.githubusercontent.com/3057651/101052495-f5c2b480-3586-11eb-8416-7b05d3884541.png)

**Comment by ercrema** [comment]
Very odd - could send the data for this one as well?

**Comment by ercrema** [comment]
Fixed in c571e5423f08e892368321198a7ddbdc5bf37a4d
