### ISSUE TITLE
summary with multiple probabilities and BC/AD scale

### ISSUE THREAD

**Issue by nfrerebeau** [ahb108/rcarbon#53]
Summarizing several calibrated dates causes a warning if we pass several probabilities as arguments and causes an error if we change the time scale to BC/AD:

``` r
x <- rcarbon::calibrate(x = c(4000, 4200), errors = c(30, 40))
summary(x) # OK
```

``` r
summary(x, prob = 0.95) # OK
summary(x, prob = c(0.68, 0.95)) # warning
Warning message:
In if (is.na(prob)) { :
  la condition a une longueur > 1 et seul le premier élément est utilisé
```

This warning can be prevented if `summary.CalDates()` tests for missing values with `anyNA()` instead of `is.na()`.

``` r
summary(x, calendar = "BP") # OK
summary(x, calendar = "BCAD") # error
Error in if (any(x < 0)) { : 
  valeur manquante là où TRUE / FALSE est requis 
```

The error can be avoided by checking for missing values in `BPtoBCAD()` (same in `BCADtoBP()`).

I've changed the code [on my side](https://github.com/nfrerebeau/rcarbon/commit/6108219fed37ad24376894edde48da274ae4ce5b), if it is ok with you I can make a PR.

**Comment by ercrema** [comment]
Thanks for spotting this and suggesting a fix - and yes please do make a PR.
