### ISSUE TITLE
Y Axis Scale in Multiplot

### ISSUE THREAD

**Issue by IanMoffat** [ahb108/rcarbon#56]
Hi Enrico,
Thanks for a fantastic package!

I love the ability to plot multiple radiocarbon dates using multiplot but it would be great to be able to define the values on the y axis.  For example, where dates are plotted in stratigraphic order, it would be very useful to be able to reference the depth to each sample.

For example, when calibrating the attached set of dates using the code below

AllCSVDates<-calibrate(x=Kwamter14C$`14C B.P. (CRA)`,ids = Kwamter14C$`Lab Code`, errors=Kwamter14C$`Standard Deviation`,calCurves = Kwamter14C$'Cal Curves', resOffsets = Kwamter14C$'DeltaR', resErrors = Kwamter14C$'Error')

I have plotted them using this code
multiplot(AllCSVDates,decreasing=NULL,rescale=TRUE,HPD=TRUE,credMass = 0.95,label=TRUE,ylab="Depth",ydisp=TRUE)

Which creates a y axis with a default scale but I would like to show the depth of each sample from the original Kwamter14C CSV.

Is this currently possible and, if not, could I suggest this as a future enhancement please?

Cheers,
Ian

[Kwamter14C_V2.csv](https://github.com/ahb108/rcarbon/files/7103022/Kwamter14C_V2.csv)

**Comment by ercrema** [comment]
Hi @IanMoffat 

> Which creates a y axis with a default scale but I would like to show the depth of each sample from the original Kwamter14C CSV.

Not sure what you mean by putting a different y-axis scale. Are you thinking of something typically seen in age-depth models where the position of each calibrated date along the y-axis represent their position in the deposit? If that's the case `multiplot()` won't be able to do this and it would require a substantial re-write, if not a separate function I'm afraid. We might eventually work on this but in the meanwhile I would suggest using [Bchron](https://cran.r-project.org/web/packages/Bchron/index.html) (see example in their [vignette](https://cran.r-project.org/web/packages/Bchron/vignettes/Bchron.html)).

**Comment by IanMoffat** [comment]
Hi @ercrema 
Thanks very much for your reply and sorry that my question wasn't clear!
While a truly scalable Y axis (as you rightly suggest is possible in Bchron) would be fantastic, I wonder if it is possible to specify the values that show up in the y axis when you use  ydsip=TRUE argument?  Currently this displays 0-1 scales for each individual sample but it would be useful if this could show other information such as depth, stratigraphic unit etc.  I have attached an example image based on the code in the question above.
Many thanks,
Ian
![Kwamter_RCarbon](https://user-images.githubusercontent.com/40761075/132154622-0fdc5791-77ab-4c5b-918a-b2694fecd0e6.png)

**Comment by ercrema** [comment]
Ok - so if what you are looking for is just an annotation instead of the y-axis then it's more flexible to do this manually as follows:

```
ygap = 0.2
multiplot(AllCSVDates,decreasing=NULL,rescale=TRUE,HPD=TRUE,credMass = 0.95,label=TRUE,ylab="Depth (in cm)",ydisp=FALSE,gapFactor = ygap)
text(x=rep(1400,length(AllCSVDates)),y=seq((1+ygap)/2,by=1+ygap,length.out=length(AllCSVDates)),labels=Kwamter14C$Mean.Depth..cm.below.surface.)
```

You can manually adjust the position of these labels along the x-axis using the BP years (if BC/AD you would need to use the minus sign for BC years). The y-axis is a bit more complicated as it involves the parameter `ygap` - this just defines the  vertical spacing between the distributions so the script above enables you to adjust them and making sure that the labels are right in the middle of each. You can of course make them look more pretty  (see [tidy_radiocarbon]( https://stratigraphr.joeroe.io/articles/tidy_radiocarbon.html) for example). 

![Screenshot_2021-09-06_09-04-03](https://user-images.githubusercontent.com/2821047/132182215-8e20ce55-14d3-425f-9b94-0909aad0d5fc.png)

**Comment by IanMoffat** [comment]
Thanks @ercrema, that is very useful!  I also hadn't seen tidy_radiocarbon previously so will check that out.

One small issue, the null argument in multiplot seems to invert the original order of the samples.  It's very likely that there is an issue in my code rather than Rcarbon but I was only able to resolve this by flipping the order in the original csv so it might be worth checking out.

Thanks again for your help and for the great package!
