### ISSUE TITLE
Plot.SpdModleTest function Unable to display positive and negative area

### ISSUE THREAD

**Issue by CGL5230** [ahb108/rcarbon#57]
Using the SPD model to analyze the carbon 14 data, the bbty parameter is “f” in the plot function is used to draw the positive and negative  area, but the area cannot be displayed. However, the summary function can find the significant area.
`library(openxlsx)
data<-read.xlsx(file.choose())
caldates <- calibrate(x=data$BP, errors=data$SD, normalised=FALSE)
bins <- binPrep(sites=data$SiteName, ages=data$BP, h=50)
nsim=200 #Number of simulations
expnull <- modelTest(caldates, errors=data$SD, bins=bins, nsim=nsim, runm=50,ncores = 3,
                     timeRange=c(8000,1000), model="exponential", datenormalised=FALSE)
#plot(expnull, xlim=c(8000,1000))
#round(expnull$pval,4) #p-value
summary(expnull)
plot(
  expnull,
  calendar = "BP",
  type = "spd",
  ylim = c(0,0.2),
  xlim = c(8000,1000),
  col.obs = "black",
  col.env = rgb(0, 0, 0, 0.2),
  lwd.obs = 0.5,
  xaxs = "i",
  yaxs = "i",
  bbty = "f",
  bbtyRet = TRUE,
  drawaxes = TRUE
)
`
the result figure:
![image](https://user-images.githubusercontent.com/57136380/139667117-bb9f7ee6-b1b8-45f9-a5d1-1587a1a94f00.png)
the summary result:
![image](https://user-images.githubusercontent.com/57136380/139667128-c15321d3-767e-45ca-a81d-b690d8cbfb42.png)

**Comment by ercrema** [comment]
Hi,  I tested the code with another dateset and I am failing to reproduce the problem. I'm afraid that in order to help I would need have access to the data so I can reproduce the error. A couple of questions:

1. Which version of rcarbon are you using?
2. Does the problem arises when you simply run `plot(expnull)`? 
3. The argument `col.env` is actually available only for results of the `permTest` and not for the results `modelTest`. You should have received a warning message? 
4. Notice that `bbtyRet = TRUE` would work only when `bbty = "b"`.

**Comment by CGL5230** [comment]
Thank you for your reply.
Q1:  The version 1.4.2
Q2:  Actually,  I got a warning message:"In modelTest(caldates, errors = data$SD, bins = bins, nsim = nsim,  :
  edgeSize reduced", but not irun plot function. It is  at **modelTest** processing.
Q3:  Actually, the first origin script is not including **col.env**. I do not receive a warning message.
Q4:  I test change **bbtyRet = FALSE**, the problem still can not fix.
my data :
[henan.xlsx](https://github.com/ahb108/rcarbon/files/7453166/henan.xlsx)
my code:
library(openxlsx)
data<-read.xlsx(file.choose())
caldates <- calibrate(x=data$BP, errors=data$SD, normalised=FALSE)
bins <- binPrep(sites=data$SiteName, ages=data$BP, h=50)
nsim=200 #Number of simulations
expnull <- modelTest(caldates, errors=data$SD, bins=bins, nsim=nsim, runm=50,ncores = 3,
                     timeRange=c(8000,1000), model="exponential", datenormalised=FALSE)
#plot(expnull, xlim=c(8000,1000))
plot(expnull)
#round(expnull$pval,4) #p-value
summary(expnull)

**Comment by ercrema** [comment]
That is very strange... I used your code and regions outside the simulation envelope are highlighted correctly... (see below)
After the `plot(expnull)`, could you try running the following code?

`polygon(x = c(7000,6000,6000,7000),y=c(0.1,0.1,0.15,0.15),col=rgb(0.7,0,0,0.2),border=NA)`

and see if it draws a square rectangle? And if it doesn't could you try with this:

`polygon(x = c(7000,6000,6000,7000),y=c(0.1,0.1,0.15,0.15),col=1,border=NA)`






![Screenshot_2021-11-01_13-49-55](https://user-images.githubusercontent.com/2821047/139682198-c3bec26d-417e-4b6c-95a8-f1a0c82a5d36.png)

**Comment by CGL5230** [comment]
Yep...I  try my code again and the picture as usual...  But the rectangle could be draw by those code...  I Confuse it....
![image](https://user-images.githubusercontent.com/57136380/139684442-f8ffa57f-1463-4e4c-af66-c502d7b3397e.png)
![image](https://user-images.githubusercontent.com/57136380/139684525-873e40db-7a49-4eaa-92da-d0d8f03034fb.png)
may some issues about dependent package version? may be other?

**Comment by ercrema** [comment]
Very strange... I was hoping it was something to do with with alpha transparency but the fact that you can display the first rectangle means that this is not the case... Does this happen with other datasets? Could you try the following and see what happens ?

```
data(emedyd)
emedyd <- subset(emedyd,Region=='1')
caldates <- calibrate(x=emedyd$CRA, errors=emedyd$Error, normalised=FALSE)
bins <- binPrep(sites=emedyd$SiteName, ages=emedyd$CRA, h=50)
set.seed(123)
expnull <- modelTest(caldates, errors=emedyd$Error,nsim=100,ncores=3, runm=50,timeRange=c(16000,9000), model="exponential", datenormalised=FALSE)
plot(expnull)
```

**Comment by ercrema** [comment]
Also could you show me the results of your `sessionInfo()`

**Comment by CGL5230** [comment]
Yes, i try. But the area seem disappear.. I really hope may be some environmental problem, AND i will pick other computer try do the math.
![image](https://user-images.githubusercontent.com/57136380/139687290-3527d6de-74f3-48cf-80e3-11d255b4a761.png)
![image](https://user-images.githubusercontent.com/57136380/139687379-62d9c5a1-2943-451b-aedf-a94bcdb7b1f9.png)

**Comment by ercrema** [comment]
Not really a solution but could you try the following:

```
bb<-plot(expnull,bbty = 'b')
boomBlocks <- bb$booms
bustBlocks <- bb$busts
for (i in 1:length(boomBlocks)){
      polygon(c(boomBlocks[[i]][[2]],rev(boomBlocks[[i]][[2]])),c(rep(+100,length(boomBlocks[[i]][[1]])),rep(-100,length(boomBlocks[[i]][[1]]))),col=rgb(0.7,0,0,0.2),border=NA)
}
for (i in 1:length(bustBlocks)){
      polygon(c(bustBlocks[[i]][[2]],rev(bustBlocks[[i]][[2]])),c(rep(+100,length(bustBlocks[[i]][[1]])),rep(-100,length(bustBlocks[[i]][[1]]))),col=rgb(0,0,0.7,0.2),border=NA)
}
```

**Comment by CGL5230** [comment]
I seem like i find the reason... Maybe the environment of computer have some issues, maybe the windows10 update....
I really appreciate it for your help!
![image](https://user-images.githubusercontent.com/57136380/139694421-d3aa347f-bd6a-43bf-82ce-757169622b90.png)

**Comment by ercrema** [comment]
Glad to see that is working now! :) I'll close the issue
