### ISSUE TITLE
Doubt About simulation envelope is  FLAT

### ISSUE THREAD

**Issue by CGL5230** [ahb108/rcarbon#58]
Here I am,again.Thank you for your effort about my question last week. But, i noticed that the simulation envelope is  **FLAT**.
![image](https://user-images.githubusercontent.com/57136380/140287739-a26fcbf5-dcc9-433e-9cbd-104f0bac790c.png)
I read the paper(Crema, E., & Bevan, A. (2021). INFERENCE FROM LARGE SETS OF RADIOCARBON DATES: SOFTWARE AND METHODS. <i>Radiocarbon,</i> <i>63</i>(1), 23-39. doi:10.1017/RDC.2020.95) and found maybe  just normalized problem.
![image](https://user-images.githubusercontent.com/57136380/140288441-0df03dc2-8203-49fb-9479-73bc7578bd44.png)
When I came to read the help of **calibrate** function ,the **"normalised "** parameter default is **TRUE**.I just have some doubt 
 and want to know how to fix it.
my data and code as usual as the issues named "Plot.SpdModleTest function Unable to display positive and negative area #57"

**Comment by ercrema** [comment]
Your observed SPD has a rise and fall, so when you fit an exponential curve the lines looks almost flat (if you check the fitted curve typing `expnull$fit$PrDens` you would notice this is not constant). This is not a bug, a normalisation issue or a problem with your code but a feature of `modelTest`. Whether testing against this particular fitted model is the right thing to do is a separate issue that depends on your purpose and intent.
