### ISSUE TITLE
Feature wish: stackspd sorting matches factor levels (or something else)

### ISSUE THREAD

**Issue by cmbarton** [ahb108/rcarbon#62]
The sorting of the groups for stackspd is not clear, but I **think** it is the default order of the grouping variable in the data.frame. This can be pretty random. 

It would be better if either a) there is an explicit way to order these or at least b) using the level of the grouping variable if it is a factor or alphabetically if it is character.

**Comment by ercrema** [comment]
I think this is a good idea. Probably ordered factor is the simplest option - would be tempted to leave ordering in the data.frame in case user supply unordered factors or characters for backward compatibility. Thanks Mike - will work on it once I have a moment.

**Comment by ercrema** [comment]
This is now addressed in commit 1b17653800763ee04e6f6b402e3067b35d127b3e. The stackSPD class object would store the spd with the order of the factor levels.
