### ISSUE TITLE
Anyone run into 'Error in t(w) %*% obsMatrix : non-conformable arguments' when using sptest() ? 

### ISSUE THREAD

**Issue by kaos000** [ahb108/rcarbon#64]
I am performing sptest() on my data. Cannot figure out how to make it work with binned sites. Works when 'binning' individual samples. Tried various approaches inlcluding transpose t(), NAs, timerange, h, adjustments to raw data

**Comment by ercrema** [comment]
Hi @kaos000,
I need a reproducible script in order to diagnose your issue. Can you upload a sample script generating the error with a dummy dataset?
E

**Comment by kaos000** [comment]
Great! Where should I send it?

**Comment by kaos000** [comment]
@ercrema 
Great! Thank you. Here it is

[dummy_set.csv](https://github.com/ahb108/rcarbon/files/11634390/dummy_set.csv)


`library(rcarbon)
library(sf)
library(sp)
library(rnaturalearth)
library(rnaturalearthhires) 
library(dplyr)


test_spatial <-read.csv('dummy_set.csv')
test_spatial_f <- test_spatial %>% mutate_if(is.character,as.factor)
test_spatial_f <-test_spatial_f %>% mutate_at(vars(Site), factor)


testsub <-subset(test_spatial_f,BP<=1950&BP>=1000)

testsub_dates <- calibrate(testsub$BP,testsub$STD,normalised=FALSE,verbose=FALSE)
testsub_bins <- binPrep(sites=testsub$LabNo,ages=testsub$BP,h=50)


sites <- unique(data.frame(id=testsub$Site,lon=testsub$LONG,lat=testsub$LAT))
sites  <- st_as_sf(sites,coords=c('lon','lat'),crs=4258)

breaks <- seq(1950,1000,-50) 
timeRange <- c(1950,1000) #time range in calBP

testspd = spd(x = testsub_dates,bins=testsub_bins,timeRange = timeRange)
plot(spd2rc(testspd,breaks = breaks),calendar = "BCAD", main="Test")


testspatial <- sptest(
  calDates=testsub_dates,
  timeRange=timeRange,
  bins=testsub_bins,
  locations=sites,
  locations.id.col = 'id',
  breaks=breaks,
  h = 50,
  kernel = "gaussian",
  rate = expression((t2/t1)^(1/d) - 1),
  nsim = 100,
  runm = NA,
  permute = "locations",
  ncores = 1,
  datenormalised = FALSE,
  verbose = TRUE,
  raw = FALSE
)

win  <- st_geometry(ne_states(geounit = c("norway", "sweden"),returnclass='sf'))
xrange <- st_bbox(sites)[c(1,3)]
yrange <- st_bbox(sites)[c(2,4)]


par(mar=c(1,1,4,1),mfrow=c(1,3))
plot(win,col="antiquewhite3", border="antiquewhite3",xlim=xrange,ylim=yrange)
plot(scanspatial,index=10, option="test", add=TRUE, legend=TRUE, legSize=0.7, location="topleft")

plot(win,col="antiquewhite3", border="antiquewhite3",xlim=xrange,ylim=yrange)
plot(scanspatial,index=11, option="test", add=TRUE)

plot(win,col="antiquewhite3", border="antiquewhite3",xlim=xrange,ylim=yrange)
plot(scanspatial,index=12, option="test", add=TRUE)

plot(win,col="antiquewhite3", border="antiquewhite3",xlim=xrange,ylim=yrange)
plot(scanspatial,index=10, option="raw", add=TRUE, breakRange=c(-0.005,0.005))

plot(win,col="antiquewhite3", border="antiquewhite3",xlim=xrange,ylim=yrange)
plot(scanspatial,index=11, option="raw", add=TRUE, breakRange=c(-0.005,0.005))

plot(win,col="antiquewhite3", border="antiquewhite3",xlim=xrange,ylim=yrange)
plot(scanspatial,index=12, option="raw", add=TRUE, breakRange=c(-0.005,0.005))
`

**Comment by ercrema** [comment]
@kaos000 I think the source of the problem is that your dataset includes sites with the same name but different coordinates (e.g. S41 has 12.99082, 55.54724  but also 13.01215, 55.54769 and 14.21617, 56.07594). As a result when you run `sites <- unique(data.frame(id=testsub$Site,lon=testsub$LONG,lat=testsub$LAT))` you have duplicate sitenames, and sptest ends up with differently sized matrices.

**Comment by kaos000** [comment]
@ercrema Thank you so much for the quick help, that's awesome! I will fix ithis up and see how it runs.
//K

**Comment by ercrema** [comment]
No worries - let me know if this fixes your problem. If not we can re-open the issue.

**Comment by kaos000** [comment]
@ercrema That solved it!
